const projects = [
  {
    id: 1,
    title: "2048 Game",
    category: "Web App",
    description: "A classic 2048 puzzle game built using JavaScript.",
    tech: ["HTML", "CSS", "JavaScript"],
    developers: ["Sumanth N"],
    icon: "bi-grid-3x3-gap",
    githubUrl: "",
    liveUrl: "https://absolutelysumanth.github.io/2048_game/",
    rating: 0,
    reviews: []
  },
  {
    id: 2,
    title: "Tic Tac Toe",
    category: "Web App",
    description: "Interactive Tic Tac Toe game with clean UI.",
    tech: ["HTML", "CSS", "JavaScript"],
    developers: ["Sumanth N"],
    icon: "bi-x-square",
    githubUrl: "",
    liveUrl: "https://absolutelysumanth.github.io/tic-tac-toe_game/",
    rating: 0,
    reviews: []
  },
  {
    id: 3,
    title: "Sudoku Game",
    category: "Web App",
    description: "Sudoku puzzle solver and playable game.",
    tech: ["HTML", "CSS", "JavaScript"],
    developers: ["Sumanth N"],
    icon: "bi-puzzle",
    githubUrl: "",
    liveUrl: "https://absolutelysumanth.github.io/sudoku_game/",
    rating: 0,
    reviews: []
  },
  {
    id: 4,
    title: "Flip a Coin",
    category: "Web App",
    description: "Simple coin toss simulator.",
    tech: ["HTML", "CSS", "JavaScript"],
    developers: ["Sumanth N"],
    icon: "bi-coin",
    githubUrl: "",
    liveUrl: "https://absolutelysumanth.github.io/flip-a-coin/",
    rating: 0,
    reviews: []
  },
  {
    id: 5,
    title: "Roll a Die",
    category: "Web App",
    description: "Dice rolling simulator with random output.",
    tech: ["HTML", "CSS", "JavaScript"],
    developers: ["Sumanth N"],
    icon: "bi-dice-5",
    githubUrl: "",
    liveUrl: "https://absolutelysumanth.github.io/roll-a-die/",
    rating: 0,
    reviews: []
  },
  {
    id: 6,
    title: "Endless Drive",
    category: "Web App",
    description: "An endless driving game with continuous road movement and interactive gameplay.",
    tech: ["HTML", "CSS", "JavaScript"],
    developers: ["Sumanth N"],
    icon: "bi-car-front",
    githubUrl: "",
    liveUrl: "https://absolutelysumanth.github.io/endless_drive_code_v/",
    rating: 0,
    reviews: []
  },
  {
    id: 7,
    title: "Glory Gym",
    category: "Web App",
    description: "A smart workout suggestion app that recommends exercises based on basic user inputs.",
    tech: ["HTML", "CSS", "JavaScript"],
    developers: ["Gurupadayya Odeyar "],
    icon: "bi-heart-pulse",
    githubUrl: "",
    liveUrl: "https://gurupadayyaodeyar.github.io/GloryGym/",
    rating: 0,
    reviews: []
  },
  {
    id: 8,
    title: "Stealth Text",
    category: "Web App",
    description: "A steganography tool that hides encrypted text inside images, retrievable using a secret key.",
    tech: ["HTML", "CSS", "JavaScript"],
    developers: ["Gurupadayya Odeyar "],
    icon: "bi-shield-lock",
    githubUrl: "",
    liveUrl: "https://gurupadayyaodeyar.github.io/StealthText/",
    rating: 0,
    reviews: []
  },
  {
    id: 9,
    title: "Bill Maadi",
    category: "Web App",
    description: "A simple billing tool designed for small grocery shop owners with minimal technical knowledge. It features an easy-to-use interface to add items, calculate totals, and generate bills quickly.",
    tech: ["HTML", "CSS", "JavaScript", "Firebase"],
    developers: ["Sujay M H"],
    icon: "bi-receipt",
    githubUrl: "",
    liveUrl: "https://bill-maadi.vercel.app/",
    rating: 0,
    reviews: []
  },
  {
    id: 10,
    title: "Mood Music Recommender",
    category: "Web App",
    description: "A mood-based music recommendation app that suggests songs based on the user's current mood.",
    tech: ["HTML", "CSS", "JavaScript"],
    developers: ["Khazi Mohammed Fahad"],
    icon: "bi-music-note-beamed",
    githubUrl: "",
    liveUrl: "https://fahadkhazi0-ops.github.io/mood_music_recommender/",
    rating: 0,
    reviews: []
  },
  {
    id: 11,
    title: "Academic Dashboard - Semester Edition",
    category: "Web App",
    description: "An academic tracker for students to manage semester-related activities and progress.",
    tech: ["HTML", "CSS", "JavaScript"],
    developers: ["Vaibhav Shettar"],
    icon: "bi-mortarboard",
    githubUrl: "",
    liveUrl: "https://ihatecollege.fun/",
    rating: 0,
    reviews: []
  },
  {
    id: 12,
    title: "Student Management System",
    category: "Web App",
    description: "A student-tracking system for academic institutions to manage and monitor student information.",
    tech: ["HTML", "CSS", "JavaScript"],
    developers: ["Vaibhav Shettar"],
    icon: "bi-person-lines-fill",
    githubUrl: "",
    liveUrl: "https://student-tracking-system-sigma.vercel.app/",
    rating: 0,
    reviews: []
  },
  {
    id: 13,
    title: "Sanctum - The Mind of Vaibhav",
    category: "Web App",
    description: "A personal digital archive to categorize, connect, and explore thoughts with a knowledge graph, markdown editor, and real-time cloud sync.",
    tech: ["React JS", "Supabase", "JavaScript"],
    developers: ["Vaibhav Shettar"],
    icon: "bi-journal-richtext",
    githubUrl: "",
    liveUrl: "https://sanctum-mindvault.vercel.app/",
    rating: 0,
    reviews: []
  },
  {
    id: 14,
    title: "Journal for Trading",
    category: "Web App",
    description: "A trading journal project for recording and tracking trades.",
    tech: ["HTML", "CSS", "JavaScript"],
    developers: ["Vaibhav Shettar"],
    icon: "bi-graph-up-arrow",
    githubUrl: "https://github.com/vaibhavforeal/trade-tracker",
    liveUrl: "https://github.com/vaibhavforeal/trade-tracker",
    rating: 0,
    reviews: []
  },
  {
    id: 15,
    title: "Shannon AI Pentester GUI",
    category: "Web App",
    description: "A GUI-based tool for AI-powered penetration testing, implementing Shannon-based security concepts.",
    tech: ["JavaScript", "HTML", "CSS"],
    developers: ["Vaibhav Shettar"],
    icon: "bi-shield-lock-fill",
    githubUrl: "https://github.com/vaibhavforeal/Shannon-Security-GUI-version",
    liveUrl: "https://github.com/vaibhavforeal/Shannon-Security-GUI-version",
    rating: 0,
    reviews: []
  },
  {
    id: 16,
    title: "Election Process Education",
    category: "Web App",
    description: "An AI-powered civic education tool that helps Karnataka citizens understand the election process in English & ಕನ್ನಡ with step-by-step guidance, constituency lookup, and live Q&A.",
    tech: ["HTML", "CSS", "JavaScript", "Firebase", "Gemini API", "Google Cloud"],
    developers: ["Sujay M H"],
    icon: "bi-people-fill",
    githubUrl: "",
    liveUrl: "https://election-process-education-602894482227.us-central1.run.app/",
    rating: 0,
    reviews: []
  }

];